### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by pgrimaud**
Hello,

This PR will fix : 

- 1 typo in `docs/docs/0.4.0/documentation/backends.md`
- 1 typo in `docs/docs/0.4.0/documentation/dps-and-data-model.md`
- 1 typo in `docs/docs/0.4.0/documentation/networking.md`
- 1 typo in `docs/docs/0.4.0/documentation/security.md`
- 1 typo in `docs/docs/0.4.0/policies/applying-policies.md`
- 2 typos in `docs/docs/0.4.0/policies/mutual-tls.md`
- 2 typos in `docs/docs/0.4.0/policies/traffic-log.md`

Cheers! :robot:

### CODE REVIEW

**Comment by pgrimaud** [comment]
I also found typos on docs < 0.4.

I could updated my PR with, if you want? 😄

**Comment by devadvocado** [comment]
Hey @pgrimaud, thanks for the help! Really appreciate it 😄 

If you want to update all the typos in one PR, that sounds great to me

**Comment by pgrimaud** [comment]
@devadvocado Here we are! Ton of changes 😄

**Comment by devadvocado** [comment]
@pgrimaud changes look good to me, thanks for the help!

**Comment by devadvocado** [comment]
"Typo man" 🤣

**Comment by subnetmarco** [comment]
Thanks for the contribution @pgrimaud !

**Comment by pgrimaud** [comment]
@devadvocado 🥴

**Pull request merged**
