### PR TITLE
Logo update

### PR DESCRIPTION
**Pull request by bloqhead**
## Logo updates on:
- All documentation diagram images
- All favicons, Apple icons and other touch icons
- The main logo in the masthead
- OpenGraph images for Facebook and Twitter

## Additional changes:
- Adds cache busting to ensure these images are force-updated in the user's browser
- Updates all web manifest and browser config files
- Adds a new icon for pinned tabs in Safari
- Gets rid of some unneeded icons
- Updates all of the required meta data for these items

### CODE REVIEW

**Comment by subnetmarco** [comment]
This needs to be opened against `next`, I just changed that.

**Comment by bloqhead** [comment]
@subnetmarco thank you for catching that. I keep forgetting to change that.

**Comment by subnetmarco** [comment]
@bloqhead please update the logo only in the latest version (`0.4.0` in the docs) do not update it for the older versions

**Comment by subnetmarco** [comment]
@bloqhead basically add the new diagrams in the `docs/.vuepress/public/images/docs/0.5.0/` folder and replace all the images in the docs at `docs/docs/0.4.0/` with link that point to the new `0.5.0` folder (and therefore the new diagrams with the new logo).

**Comment by bloqhead** [comment]
@subnetmarco I've restored the doc images that have the old logo for versions 0.1.0 to 0.2.0. The 0.3.2 folder didn't require any changes because there were no diagrams with the logo on it.

For the 0.4.0 docs, there was a lot of crossover use of diagram images from 0.2.0 and 0.3.2, so I've copied all of the used images from the 2 folders, put them into the 0.4.0 images folder, and then replaced all image references in the 0.4.0 docs. Now all of the images we link to in the 0.4.0 docs are also from the 0.4.0 folder so that we can reduce confusion and make future updates easier (e.g. modifying images for 0.4.0). All 0.4.0 diagrams have the new logo now.

I haven't created a 0.5.0 image folder yet until the doc updates are finished. I figured if the diagrams between 0.4.0 and 0.5.0 aren't changing (aside from the logo), then we can reference the 0.4.0 images in the 0.5.0 docs and reduce duplicate images.

**Comment by subnetmarco** [comment]
@bloqhead sorry for the confusion, but what I meant is that all diagrams with the new logo should be added in the `docs/.vuepress/public/images/docs/0.5.0/` images folder which already exists in `next`.

Then, as a next step, we are going to be updating the `0.4.0` docs with links to the newly added diagrams in that `docs/.vuepress/public/images/docs/0.5.0/` folder.

**Comment by bloqhead** [comment]
@subnetmarco I've added a 0.5.0 folder for doc images and copied over the updated diagrams to that folder. So when we're ready to cut a new version, we can update the image paths accordingly in the 0.4.0 folder. All favicons, touch icons, and the OpenGraph image should no longer be cached. I added a randomized string to the end of each image that forces the browser to load the new ones. I've tested it in Firefox, Chrome, and Safari and see the new images in all of them.

**Pull request merged**
